spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/board
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: draw
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

  jwt:
    secret: 2021!!ZorupMSA

  messages:
    basename: i18n/exception
    encoding: UTF-8

  devtools:
    livereload:
      enabled: true

server:
  port: 8080

fcm:
  keypath: ./alarm-1830c-firebase-adminsdk-vbgdk-636d5e3a1c.json