# 로컬 환경에서 사용시 local 을 프로파일로 지정해 사용해야 정상동작함


# 로컬 개발용
spring:
  profiles:
    group:
      "local":"local_url,common"

---

# 운영서버 배포용
spring:
  profiles:
    group:
      "prod":"prod_url,common"

---


# 로컬 개발용 url설정, 본인 환경에 맞게 변경해서 사용
spring:
  config:
    activate:
      on-profile: local_url
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: mariadb

server:
  port: 8082

---

# 운영서버 배포용 url설정
spring:
  config:
    activate:
      on-profile: prod_url
  datasource:
    url: jdbc:mariadb://13.124.121.251:3306/main
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: mariadb

server:
  port: 8082

---

# 공통부분 작성
spring:
  config:
    activate:
      on-profile: "common"
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
      # hibernate:
    # ddl-auto: create

  jwt:
    secret: 2021!!ZorupMSA

  messages:
    basename: i18n/exception
    encoding: UTF-8

